# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{metajp}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Paul Narowski"]
  s.date = %q{2010-01-25}
  s.description = %q{These tools help setup and install plugins}
  s.email = %q{jnarowski@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/metajp.rb",
     "lib/metajp/templates/admin.rb",
     "lib/metajp/templates/authlogic.rb",
     "lib/metajp/templates/base.rb",
     "lib/metajp/templates/capistrano.rb",
     "lib/metajp/templates/config/deploy.rb",
     "lib/metajp/templates/controllers/admin/admin_controller.rb",
     "lib/metajp/templates/controllers/users/activations_controller.rb",
     "lib/metajp/templates/controllers/users/password_resets_controller.rb",
     "lib/metajp/templates/git.rb",
     "lib/metajp/templates/models/notifier.rb",
     "lib/metajp/templates/models/user.rb",
     "lib/metajp/templates/models/user_session.rb",
     "lib/metajp/templates/public/javascripts/application.js",
     "lib/metajp/templates/public/stylesheets/application.css",
     "lib/metajp/templates/rspec.rb",
     "lib/metajp/templates/views/admin.html.erb",
     "lib/metajp/templates/views/application.html.erb",
     "test/helper.rb",
     "test/helper.rb",
     "test/test_metajp.rb"
  ]
  s.homepage = %q{http://github.com/jnarowski/metajp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Shared functionality for rails apps}
  s.test_files = [
    "test/helper.rb",
     "test/test_metajp.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

